---

- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  become: False
  vars_files:
    - ../group_vars/vault

  tasks:
    - include: test-vault-credentials.yml

    - name: Create token with specified name
      vault_token:
        token: "{{ vault_token }}"
        tls: off
        state: present
        id: 'test-token'
        num_uses: 1
        no_default_policy: true
    - name: Create token with specified name (should be no change)
      vault_token:
        token: "{{ vault_token }}"
        tls: off
        state: present
        id: 'test-token'

    - name: Create token with specified name
      vault_token:
        token: "{{ vault_token }}"
        tls: off
        state: present
        id: 'test-token-orphan'
        no_parent: true

    - name: Create token with specified name (should be no change)
      vault_token:
        token: "{{ vault_token }}"
        tls: off
        state: present
        id: 'test-token-orphan'
        no_parent: true

    - name: Create token with no name
      vault_token:
        token: "{{ vault_token }}"
        tls: off
        state: present

#    - name: Remove token
#      vault_token:
#        token: "{{ vault_token }}"
#        tls: off
#        state: revoke
#        id: 'test-token'
#
#    - name: Remove token (should be no changes)
#      vault_token:
#        token: "{{ vault_token }}"
#        tls: off
#        state: revoke
#        id: 'test-token'
